var fakeData = { 
 "photo_title": "Wheatfield in afternoon light",
 "detail": "Hey guys! Checkout this beautiful place!",
 "review": [{"user_id": "shadowplayer", "user_comment": "What a nice place!"},
 {"user_id": "shadowplayer2", "user_comment": "Please Adjust your fan art accordingly﻿"},
 {"user_id": "Hail Whydra", "user_comment": "He's got the best anti-aging cream﻿"},
 {"user_id": "Van Hendrix", "user_comment": "Ashes is old enough to drive but not enough to retire"},
 {"user_id": "Hexa Coyerrr", "user_comment": "Ash is secretly the ultimate life form﻿"},
 {"user_id": "Justin Y.", "user_comment": "Ash is secretly the ultimate life form﻿"},
 {"user_id": "Fire_Power Productions", "user_comment": "Road to 100 subs﻿"},
 {"user_id": "Kane Aquino", "user_comment": "Top 10 most Ugliest places in the world. #1: My basement"},
 {"user_id": "42K4", "user_comment": "ndonesia is beautiful, too!﻿"},
 {"user_id": "Mills J", "user_comment": "Been to Palawan Philippines twice.. the place is heaven on earth﻿"},
 {"user_id": "CuzaCutuza", "user_comment": "I'm sorry but Number 10 takes the #1 spot﻿"},
 {"user_id": "Erich Scheidle", "user_comment": "Such beautiful places. To bad that we humans will probably destroy those places sooner or later."},
 {"user_id": "Nyx", "user_comment": "Where is Lofoten, Norway?﻿"},
 {"user_id": "vassili", "user_comment": "greece???﻿"},
 {"user_id": "monsteremark", "user_comment": "ive been in palawan with my boyfriend and its very surreal. proud to be a filipino﻿"},
 {"user_id": "Marios M.", "user_comment": "where is Greece ?﻿"},
 {"user_id": "Grc.", "user_comment": "Most beautiful place in the world : my bed﻿"},
 {"user_id": "Eliban Valera", "user_comment": "Look into the Caribbean"}],
 "photo_file_url":"http://mw2.google.com/mw-panoramio/photos/medium/532693.jpg",
 "upload_date": "12 March 2007", 
 "owner_id": 49870, 
 "owner_name": "Jean-Michel Raggioli"}

export default fakeData;